export const CATEGORIES = ['全部', '设计 · 海报', '写作 · 文案', '编程 · 开发', '效率 · 办公', '数据 · 分析', '营销 · 增长', '其他'];

export const REMOVED_SELF_WORKFLOW_IDS = new Set([
  'wf_seed_xhs',
  'wf_seed_palette',
  'wf_seed_translate',
  'wf_seed_codereview',
  'wf_seed_poster',
  'wf_seed_meeting',
  'wf_seed_dataclean',
  'wf_seed_social',
  'wf_seed_sql',
  'wf_seed_web_markdown'
]);

export const SEED_DATA = {
  user: null,
  workflows: [
    {
      id: 'wf_seed_picspark',
      name: 'PicSpark · 商品图 AI',
      tagline: '电商商品图智能生成 · 主图换背景 · 模特图',
      description: 'PicSpark 是专门为电商场景设计的 AI 商品图生成工具。无论你是要换背景、生成模特上身图、做节日营销海报,都能一键完成。基于扩散模型 + 视觉理解,生成质量接近专业摄影。',
      target_url: 'https://www.picspark.cn',
      type: 'recommend',
      category: '设计 · 海报',
      tags: ['电商', 'AI 生图', '中文'],
      price_model: 'cps',
      price_amount: 0,
      cover_color: '#1A5D3A',
      status: 'active',
      rating: 4.9,
      review_count: 2830,
      examples: [
        { label: '场景 · 商品换背景', text: '输入:一张白底奶粉罐照片\n输出:同一罐奶粉,但在温馨的家庭厨房场景中,自然光照明,配以新鲜水果作为陪衬' },
        { label: '场景 · 节日营销图', text: '输入:口红产品图\n输出:春节红金主题海报,口红嵌入福字图案,左下角自动留出文案区域' }
      ],
      seed_clicks: 4500,
      seed_clicks_7d: 380,
      created_at: '2026-04-15'
    },
    {
      id: 'wf_seed_xhs',
      name: '小红书爆款笔记生成',
      tagline: '输入关键词,产出符合平台调性的完整笔记',
      description: '抓住小红书的第三人称口吻、emoji 节奏、热搜词 hook。每次返回 3 种风格变体(干货向、故事向、对比向),供你按账号定位挑选。',
      target_url: 'https://flowhub.cn/run/xhs-note',
      type: 'self',
      category: '写作 · 文案',
      tags: ['小红书', '种草', '内容'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#1E3A8A',
      status: 'active',
      rating: 4.8,
      review_count: 1247,
      examples: [
        { label: '场景 · 美妆笔记', text: '输入:平价精华水 · 25-30 岁敏感肌\n输出:敏感肌姐妹冲!这瓶平价精华水我藏了三个月才舍得分享 ✨ ...' }
      ],
      seed_clicks: 2100,
      seed_clicks_7d: 210,
      created_at: '2026-04-20'
    },
    {
      id: 'wf_seed_palette',
      name: '品牌色板生成',
      tagline: '输入品牌关键词,生成完整 VI 配色方案',
      description: '基于色彩心理学和品牌定位理论,自动产出 6 色完整配色 + 主辅色应用建议 + 配色禁忌。',
      target_url: 'https://flowhub.cn/run/palette',
      type: 'self',
      category: '设计 · 海报',
      tags: ['VI', '配色', '品牌'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#B83A6B',
      status: 'active',
      rating: 4.7,
      review_count: 612,
      examples: [],
      seed_clicks: 890,
      seed_clicks_7d: 95,
      created_at: '2026-04-25'
    },
    {
      id: 'wf_seed_resume',
      name: '简历优化助手(合作方)',
      tagline: '针对岗位 JD 优化简历,给出修改建议',
      description: '上传简历 + 目标岗位描述,AI 给出针对性改写建议,包括关键词覆盖、量化成果表述、格式优化。',
      target_url: 'https://example-resume.com',
      type: 'recommend',
      category: '其他',
      tags: ['求职', '简历', '免费'],
      price_model: 'cps',
      price_amount: 8,
      cover_color: '#5B3FA8',
      status: 'active',
      rating: 4.5,
      review_count: 1842,
      examples: [],
      seed_clicks: 3200,
      seed_clicks_7d: 280,
      created_at: '2026-05-01'
    },
    {
      id: 'wf_seed_compete',
      name: '竞品监控周报(合作方)',
      tagline: '自动抓取竞品官网与社媒,产出洞察周报',
      description: '加入竞品列表 → 每周一自动生成竞品动态周报 → 邮箱推送。覆盖产品更新、价格变化、营销活动、社媒舆情。',
      target_url: 'https://example-compete.com',
      type: 'recommend',
      category: '营销 · 增长',
      tags: ['竞品', '情报', '订阅'],
      price_model: 'cpc',
      price_amount: 1.2,
      cover_color: '#B85C00',
      status: 'active',
      rating: 4.8,
      review_count: 287,
      examples: [],
      seed_clicks: 640,
      seed_clicks_7d: 72,
      created_at: '2026-05-03'
    },
    {
      id: 'wf_seed_translate',
      name: '多语言翻译大师',
      tagline: '支持 50+ 语言的智能翻译,保留语境和风格',
      description: '基于大语言模型的多语言翻译工具。不同于传统机翻,能准确理解上下文语境,保持原文风格和专业术语。支持文档批量翻译。',
      target_url: 'https://flowhub.cn/run/translate',
      type: 'self',
      category: '写作 · 文案',
      tags: ['翻译', '多语言', '文档'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#0D7377',
      status: 'active',
      rating: 4.7,
      review_count: 956,
      examples: [
        { label: '场景 · 商务邮件', text: '输入:中文商务邮件\n输出:地道的英文商务邮件,保留原文的礼貌程度和正式感' }
      ],
      seed_clicks: 1800,
      seed_clicks_7d: 165,
      created_at: '2026-04-18'
    },
    {
      id: 'wf_seed_codereview',
      name: '代码 Review 助手',
      tagline: '自动审查代码质量,发现潜在 Bug 和安全漏洞',
      description: '提交代码片段或 GitHub PR 链接,AI 自动进行代码审查。覆盖代码风格、性能优化、安全漏洞、最佳实践等维度。',
      target_url: 'https://flowhub.cn/run/codereview',
      type: 'self',
      category: '编程 · 开发',
      tags: ['代码审查', '安全', 'GitHub'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#24292E',
      status: 'active',
      rating: 4.8,
      review_count: 723,
      examples: [],
      seed_clicks: 1520,
      seed_clicks_7d: 198,
      created_at: '2026-04-22'
    },
    {
      id: 'wf_seed_poster',
      name: '节日海报生成器',
      tagline: '输入节日 + 品牌元素,生成多款营销海报',
      description: '覆盖春节、618、双 11、圣诞等 30+ 节日模板。输入品牌 Logo 和主色调,自动生成符合品牌调性的节日营销海报。',
      target_url: 'https://flowhub.cn/run/poster',
      type: 'self',
      category: '设计 · 海报',
      tags: ['海报', '营销', '节日'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#DC2626',
      status: 'active',
      rating: 4.6,
      review_count: 438,
      examples: [],
      seed_clicks: 980,
      seed_clicks_7d: 125,
      created_at: '2026-04-28'
    },
    {
      id: 'wf_seed_meeting',
      name: '会议纪要提取',
      tagline: '上传录音或文本,自动生成结构化会议纪要',
      description: '支持上传录音文件或粘贴文字记录,自动识别发言人、提取关键决策、待办事项、时间节点,生成结构化纪要并可导出。',
      target_url: 'https://flowhub.cn/run/meeting',
      type: 'self',
      category: '效率 · 办公',
      tags: ['会议', '纪要', '效率'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#7C3AED',
      status: 'active',
      rating: 4.9,
      review_count: 1102,
      examples: [],
      seed_clicks: 2350,
      seed_clicks_7d: 312,
      created_at: '2026-04-10'
    },
    {
      id: 'wf_seed_dataclean',
      name: '数据清洗助手',
      tagline: '上传 Excel/CSV,自动清洗格式化数据',
      description: '识别并修复数据中的格式不一致、重复值、缺失值、异常值。支持自定义清洗规则,处理完成后导出干净数据。',
      target_url: 'https://flowhub.cn/run/dataclean',
      type: 'self',
      category: '数据 · 分析',
      tags: ['数据', 'Excel', '清洗'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#059669',
      status: 'active',
      rating: 4.6,
      review_count: 389,
      examples: [],
      seed_clicks: 760,
      seed_clicks_7d: 88,
      created_at: '2026-05-02'
    },
    {
      id: 'wf_seed_seo',
      name: 'SEO 文章优化器(合作方)',
      tagline: '输入关键词,生成 SEO 友好的长文章',
      description: '基于搜索引擎算法分析,自动优化文章结构、关键词密度、标题层级、内链建议,提升搜索排名。',
      target_url: 'https://example-seo.com',
      type: 'recommend',
      category: '营销 · 增长',
      tags: ['SEO', '内容营销', '搜索'],
      price_model: 'cpc',
      price_amount: 0.8,
      cover_color: '#EA580C',
      status: 'active',
      rating: 4.4,
      review_count: 567,
      examples: [],
      seed_clicks: 1100,
      seed_clicks_7d: 142,
      created_at: '2026-04-30'
    },
    {
      id: 'wf_seed_contract',
      name: '合同风险审查(合作方)',
      tagline: '上传合同,AI 标注风险条款和修改建议',
      description: '基于法律知识库训练,自动识别合同中的不公平条款、缺失条款、法律风险,给出修改建议和风险等级评估。',
      target_url: 'https://example-legal.com',
      type: 'recommend',
      category: '其他',
      tags: ['法律', '合同', '风控'],
      price_model: 'cps',
      price_amount: 12,
      cover_color: '#1E40AF',
      status: 'active',
      rating: 4.7,
      review_count: 234,
      examples: [],
      seed_clicks: 520,
      seed_clicks_7d: 68,
      created_at: '2026-05-05'
    },
    {
      id: 'wf_seed_social',
      name: '社媒排期管家',
      tagline: '一键规划多平台内容日历,自动排期发布',
      description: '支持微博、抖音、小红书、公众号等主流平台。输入内容主题和发布频率,自动生成一周/月内容日历和文案草稿。',
      target_url: 'https://flowhub.cn/run/social',
      type: 'self',
      category: '营销 · 增长',
      tags: ['社媒', '排期', '内容'],
      price_model: 'pro',
      price_amount: 0,
      cover_color: '#DB2777',
      status: 'active',
      rating: 4.5,
      review_count: 678,
      examples: [],
      seed_clicks: 1350,
      seed_clicks_7d: 156,
      created_at: '2026-04-26'
    },
    {
      id: 'wf_seed_image_video',
      name: 'Image2Video 画布导演',
      tagline: 'Image2 生关键帧,拖入画布连线,再生成短视频分镜',
      description: 'FlowHub 自营的图生视频创作工作流。右侧像聊天一样用 Image2 生成关键帧,左侧画布拖拽排镜头并建立顺序,最后交给视频引擎生成 6-12 秒短视频预览。适合商品广告、短剧分镜、社媒视频和动态海报。',
      target_url: 'https://flowhub.cn/run/image-video',
      type: 'self',
      category: '设计 · 海报',
      tags: ['Image2', '图生视频', '画布'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#0F766E',
      status: 'active',
      rating: 4.9,
      review_count: 328,
      examples: [],
      seed_clicks: 1180,
      seed_clicks_7d: 224,
      created_at: '2026-05-14'
    },
    {
      id: 'wf_seed_sql',
      name: 'SQL 查询生成器',
      tagline: '用自然语言描述需求,自动生成 SQL 查询',
      description: '支持 MySQL、PostgreSQL、SQLite 等主流数据库。描述你的查询需求,自动生成优化后的 SQL,并附带执行计划分析。',
      target_url: 'https://flowhub.cn/run/sql',
      type: 'self',
      category: '编程 · 开发',
      tags: ['SQL', '数据库', '查询'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#0369A1',
      status: 'active',
      rating: 4.8,
      review_count: 1456,
      examples: [],
      seed_clicks: 2680,
      seed_clicks_7d: 345,
      created_at: '2026-04-12'
    },
    {
      id: 'wf_seed_doc_markdown',
      name: '文档转 Markdown',
      tagline: '上传 PDF / Word / HTML,转成 AI 可读 Markdown',
      description: '基于开源解析能力的 FlowHub 自营工具。支持 PDF、DOCX、HTML、TXT、MD、CSV、JSON 文件,把文档转成结构化 Markdown,方便继续交给 AI 摘要、知识库入库或内容复用。',
      target_url: 'https://flowhub.cn/run/document-markdown',
      type: 'self',
      category: '效率 · 办公',
      tags: ['文档', 'Markdown', 'PDF'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#2563EB',
      status: 'active',
      rating: 4.8,
      review_count: 216,
      examples: [
        { label: '场景 · 合同转 Markdown', text: '输入:PDF 合同\n输出:保留段落结构的 Markdown 文本,可继续摘要或提取条款' }
      ],
      seed_clicks: 1380,
      seed_clicks_7d: 176,
      created_at: '2026-05-16'
    },
    {
      id: 'wf_seed_web_markdown',
      name: '网页转 Markdown',
      tagline: '输入网址,自动提取正文并转成 Markdown',
      description: '输入公开网页地址,自动抓取正文、去掉导航和广告噪声,输出干净 Markdown。适合竞品分析、SEO 素材整理、知识库采集和文章归档。',
      target_url: 'https://flowhub.cn/run/webpage-markdown',
      type: 'self',
      category: '营销 · 增长',
      tags: ['网页抓取', 'Markdown', '知识库'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#0891B2',
      status: 'active',
      rating: 4.7,
      review_count: 184,
      examples: [
        { label: '场景 · 竞品页面采集', text: '输入:竞品落地页 URL\n输出:页面标题、摘要、正文 Markdown 和字数统计' }
      ],
      seed_clicks: 1160,
      seed_clicks_7d: 143,
      created_at: '2026-05-16'
    },
    {
      id: 'wf_seed_image_ocr',
      name: '图片 OCR 识别',
      tagline: '上传截图或图片,识别中英文文字',
      description: '基于本地开源 OCR 引擎的 FlowHub 自营工具。上传 PNG、JPG、WEBP 等图片,识别中文和英文文字,输出纯文本与 Markdown,适合截图整理、票据录入和图片资料转写。',
      target_url: 'https://flowhub.cn/run/image-ocr',
      type: 'self',
      category: '效率 · 办公',
      tags: ['OCR', '截图', '中文识别'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#7C3AED',
      status: 'active',
      rating: 4.6,
      review_count: 162,
      examples: [
        { label: '场景 · 截图转文字', text: '输入:中文网页截图\n输出:识别文本、置信度和 Markdown 结果' }
      ],
      seed_clicks: 980,
      seed_clicks_7d: 121,
      created_at: '2026-05-16'
    },
    {
      id: 'wf_seed_fitness_meal',
      name: '健身餐菜谱生成器',
      tagline: '输入现有食材,生成菜谱并计算热量和三大营养素',
      description: '参考开源 AI fitness planner 的营养计算思路,输入鸡胸肉、米饭、西兰花、鸡蛋等食材和重量,自动生成一份健身餐做法,并计算总热量、蛋白质、碳水和脂肪。第一版使用本地常见食材营养表,不依赖付费 API。',
      target_url: 'https://flowhub.cn/run/fitness-meal',
      type: 'self',
      category: '效率 · 办公',
      tags: ['健身餐', '菜谱', '热量计算'],
      price_model: 'free',
      price_amount: 0,
      cover_color: '#16A34A',
      status: 'active',
      rating: 4.7,
      review_count: 88,
      examples: [
        { label: '场景 · 减脂晚餐', text: '输入:鸡胸肉 200g、米饭 150g、西兰花 100g、鸡蛋 2个\n输出:高蛋白健身餐做法、总热量和 P/C/F 三大营养素' }
      ],
      seed_clicks: 760,
      seed_clicks_7d: 94,
      created_at: '2026-05-16'
    },
    {
      id: 'wf_seed_email',
      name: '邮件模板工厂(合作方)',
      tagline: '输入场景和要点,生成专业邮件模板',
      description: '覆盖商务沟通、客户跟进、面试邀约、催款提醒等 50+ 常见场景。支持中英双语,一键生成得体的邮件正文。',
      target_url: 'https://example-email.com',
      type: 'recommend',
      category: '效率 · 办公',
      tags: ['邮件', '商务', '模板'],
      price_model: 'cpc',
      price_amount: 0.5,
      cover_color: '#4338CA',
      status: 'active',
      rating: 4.3,
      review_count: 892,
      examples: [],
      seed_clicks: 1650,
      seed_clicks_7d: 198,
      created_at: '2026-05-06'
    }
  ],
  clicks: [],
  inline_runs: [],
  reviews: [
    { id: 'rv_1', workflow_id: 'wf_seed_picspark', user_name: '电商小赵', avatar: '赵', rating: 5, text: '主图换背景效果非常自然,比之前用 PS 抠图省了 80% 时间。强推!', date: '3 天前' },
    { id: 'rv_2', workflow_id: 'wf_seed_picspark', user_name: '跨境老王', avatar: '王', rating: 5, text: '节日海报这块尤其好用,春节促销前批量生成了 200+ 张图,客户验收一次过。', date: '1 周前' },
    { id: 'rv_3', workflow_id: 'wf_seed_picspark', user_name: '某 MCN 运营', avatar: '李', rating: 4, text: '整体很好,偶尔模特图的手部细节会有问题,需要手动挑选。', date: '2 周前' },
    { id: 'rv_4', workflow_id: 'wf_seed_picspark', user_name: '独立设计师 J', avatar: 'J', rating: 5, text: '终于不用每次都开 Photoshop 了。客户改方案也能秒响应,生产力提升 10 倍不夸张。', date: '3 周前' },
    { id: 'rv_5', workflow_id: 'wf_seed_picspark', user_name: '某护肤品牌主理人', avatar: '陈', rating: 5, text: '我们 3 人电商小团队,以前每月在外包修图上花 ¥8000+。用了 PicSpark 之后,改成 ¥39 月费,且效率更高。', date: '1 个月前' },
    { id: 'rv_6', workflow_id: 'wf_seed_picspark', user_name: '某童装店', avatar: '吴', rating: 4, text: '生成速度很快,大部分场景都能用。希望能加一个「同款多尺寸输出」的功能。', date: '1 个月前' },

    { id: 'rv_xhs_1', workflow_id: 'wf_seed_xhs', user_name: '小红书博主 @云朵', avatar: '云', rating: 5, text: '终于不用绞尽脑汁想 hook 了。生成 3 个版本任挑,平台调性把握得很准。', date: '5 天前' },
    { id: 'rv_xhs_2', workflow_id: 'wf_seed_xhs', user_name: '某美妆代运营', avatar: '美', rating: 4, text: '日常种草笔记很好用,但生硬植入广告时还是需要手动调一调。', date: '2 周前' },
    { id: 'rv_xhs_3', workflow_id: 'wf_seed_xhs', user_name: '探店小老板', avatar: '探', rating: 5, text: '一个月发了 30 篇笔记,涨粉 1200。AI 出脚本,我只需要拍照和发布。', date: '3 周前' },

    { id: 'rv_pal_1', workflow_id: 'wf_seed_palette', user_name: '品牌策划 Yuki', avatar: 'Y', rating: 5, text: '给客户做 VI 提案,色板配套理由都给了,客户接受度极高。', date: '1 周前' },
    { id: 'rv_pal_2', workflow_id: 'wf_seed_palette', user_name: '独立咖啡品牌', avatar: '咖', rating: 4, text: '配色提案很有启发性,虽然最终用了改良版,但起点比从零强 100 倍。', date: '2 周前' },

    { id: 'rv_resume_1', workflow_id: 'wf_seed_resume', user_name: '应届毕业生', avatar: '生', rating: 5, text: '关键词优化后,投简历回复率从 5% 提到 22%。', date: '4 天前' },
    { id: 'rv_resume_2', workflow_id: 'wf_seed_resume', user_name: '某互联网 PM', avatar: 'P', rating: 4, text: '量化表述建议很专业,适合写到亮点项目。', date: '2 周前' },

    { id: 'rv_compete_1', workflow_id: 'wf_seed_compete', user_name: 'SaaS 创业者', avatar: 'S', rating: 5, text: '每周一收到周报,省下我自己刷竞品官网的时间,价值无价。', date: '1 周前' },
    { id: 'rv_compete_2', workflow_id: 'wf_seed_compete', user_name: '某市场负责人', avatar: 'M', rating: 5, text: '舆情监控部分尤其好,竞品负面热搜出来 30 分钟就能收到推送。', date: '3 周前' },

    { id: 'rv_trans_1', workflow_id: 'wf_seed_translate', user_name: '外贸业务员', avatar: '贸', rating: 5, text: '终于不用一段段丢进翻译器了,整篇文档保持格式翻译,客户直接能用。', date: '3 天前' },
    { id: 'rv_trans_2', workflow_id: 'wf_seed_translate', user_name: '跨境卖家 Leo', avatar: 'L', rating: 4, text: '日语和韩语翻译质量很高,小语种偶尔需要校对,但已经比 Google Translate 好太多。', date: '1 周前' },
    { id: 'rv_code_1', workflow_id: 'wf_seed_codereview', user_name: '全栈工程师', avatar: '码', rating: 5, text: '提交 PR 前先过一遍,能发现不少低级错误和潜在的安全隐患,相当于一个不知疲倦的 reviewer。', date: '2 天前' },
    { id: 'rv_code_2', workflow_id: 'wf_seed_codereview', user_name: 'CTO 小张', avatar: '张', rating: 5, text: '团队 15 人,用了之后 code review 效率提升明显,特别是能 catch 住内存泄漏问题。', date: '1 周前' },
    { id: 'rv_meeting_1', workflow_id: 'wf_seed_meeting', user_name: '产品经理 Amy', avatar: 'A', rating: 5, text: '开会再也不用边听边记了,录音传上去自动出纪要,还能识别不同人的发言。', date: '1 天前' },
    { id: 'rv_meeting_2', workflow_id: 'wf_seed_meeting', user_name: '某咨询公司', avatar: '咨', rating: 5, text: '客户访谈直接录音转纪要,效率提升 5 倍,待办事项自动提取太好用了。', date: '5 天前' },
    { id: 'rv_sql_1', workflow_id: 'wf_seed_sql', user_name: '数据分析师', avatar: '析', rating: 5, text: '不会写复杂 JOIN 的同事也能自己查数据了,减少了运营找我写 SQL 的次数。', date: '4 天前' },
    { id: 'rv_sql_2', workflow_id: 'wf_seed_sql', user_name: '后端实习生', avatar: '实', rating: 5, text: '免费的!学 SQL 的最佳工具,生成的查询还附带解释,相当于带教了。', date: '1 周前' },
    { id: 'rv_social_1', workflow_id: 'wf_seed_social', user_name: '新媒体运营', avatar: '媒', rating: 4, text: '内容日历规划省了很多时间,但希望能支持直接对接平台 API 定时发布。', date: '3 天前' },
    { id: 'rv_contract_1', workflow_id: 'wf_seed_contract', user_name: '创业公司 CEO', avatar: 'C', rating: 5, text: '签合同前先过一遍,标出的风险条款确实专业,请律师之前先自查一遍心里有底。', date: '6 天前' }
  ],
  ad_applications: [
    {
      id: 'ad_app_1',
      advertiser_name: '北京 XX 科技',
      contact: 'contact@xxtech.cn',
      workflow_name: '某 AI 写作工具',
      workflow_url: 'https://example-writing.com',
      workflow_desc: '专业的 AI 写作平台',
      slot: 'hero',
      price_model: 'package',
      price: 4200,
      status: 'pending',
      applied_at: new Date(Date.now() - 86400000 * 2).toISOString()
    },
    {
      id: 'ad_app_2',
      advertiser_name: '上海 XX 数据',
      contact: 'biz@xxdata.com',
      workflow_name: '某 SaaS 数据平台',
      workflow_url: 'https://example-data.com',
      workflow_desc: '企业级数据分析平台',
      slot: 'category_top',
      price_model: 'cpc',
      price: 1.5,
      status: 'pending',
      applied_at: new Date(Date.now() - 86400000).toISOString()
    }
  ],
  tool_submissions: [
    {
      id: 'tool_sub_1',
      submitter_name: '陈同学',
      contact: 'chen@example.com',
      tool_name: 'PromptForge 提示词库',
      tool_url: 'https://example-promptforge.com',
      tool_desc: '面向中文运营和设计团队的提示词协作工具,支持团队收藏和版本管理。',
      category: '效率 · 办公',
      tags: ['提示词', '团队协作', '效率'],
      price_model: 'free',
      price_amount: 0,
      status: 'pending',
      admin_note: '',
      workflow_id: null,
      submitted_at: new Date(Date.now() - 43200000).toISOString(),
      reviewed_at: null
    },
    {
      id: 'tool_sub_2',
      submitter_name: '杭州某电商团队',
      contact: 'ops@example.com',
      tool_name: 'ModelShot 商品模特图',
      tool_url: 'https://example-modelshot.com',
      tool_desc: '上传平铺商品图后生成不同人群、场景和姿势的模特穿搭图。',
      category: '设计 · 海报',
      tags: ['电商', '模特图', 'AI 生图'],
      price_model: 'cpc',
      price_amount: 0.8,
      status: 'pending',
      admin_note: '',
      workflow_id: null,
      submitted_at: new Date(Date.now() - 7200000).toISOString(),
      reviewed_at: null
    }
  ]
};

export function getSeedWorkflows() {
  return SEED_DATA.workflows
    .filter((workflow) => workflow && workflow.status === 'active')
    .filter((workflow) => !(workflow.type === 'self' && REMOVED_SELF_WORKFLOW_IDS.has(workflow.id)))
    .map((workflow) => ({
      ...workflow,
      type: workflow.type === 'ad' ? 'recommend' : workflow.type,
      gallery: Array.isArray(workflow.gallery) ? workflow.gallery : [],
      logo_url: workflow.logo_url || workflow.cover_image_url || '',
      cover_image_url: workflow.cover_image_url || '',
      examples: Array.isArray(workflow.examples) ? workflow.examples : [],
      rating: Number(workflow.rating || 0),
      review_count: Number(workflow.review_count || 0),
      seed_clicks: Number(workflow.seed_clicks || 0),
      seed_clicks_7d: Number(workflow.seed_clicks_7d || 0),
      price_amount: Number(workflow.price_amount || 0)
    }));
}
